kind: ConfigMap
apiVersion: v1
metadata:
  name: couchdb
  labels:
    app: couchdb
    component: couchdb
    role: member
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: database       # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
data:
  # Erlang VM settings. The -name flag activates the Erlang distribution; there
  # should be no reason to change this setting. The -setcookie flag is used to
  # control the Erlang magic cookie. CouchDB cluster nodes can only establish a
  # connection with one another if they share the same magic cookie.
  erlflags: >
    -name couchdb
    -setcookie F2D6862C-8236-4DF9-B013-9FEDAA017972
  # CouchDB server setttings. The UUID is employed in replication checkpoints
  # and should be for unique for each cluster, but shared by all members of a
  # cluster.
  kubernetes.ini: |
    [couchdb]
    uuid = couchdb-prod
    # [admins]
    # admin = change-me
    [couch_httpd_auth]
    require_valid_user = true
