---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-system-logs
  labels:
    app: elk
    component: filebeat
    role: collect-system-logs
    release: stable      # canary
    environment: dev     # dev, qa, production
    tier: daemon         # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
data:
  filebeat.yml: |-
    filebeat:  
      prospectors:
        -
          paths:
            - "/root/.*history"
            - "/home/.*history"
            - "/var/log/*.log"
            - "/var/log/syslog"
            - "/var/log/messages"
            - "/var/log/debug"
            - "/var/log/boot"
            - "/var/log/dmesg"
            - "/var/log/autologin"
          input_type: log
          document_type: logs
    output:
      logstash:
        hosts: ["logstash:5043"]
