apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cerebro
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: elk
        component: cerebro
        role: management
    spec:
      containers:
      - name: cerebro
        imagePullPolicy: Always # IfNotPresent, Always, Never
        image: yannart/cerebro:0.6.1
        ports:
          - name: http
            containerPort: 9000
        volumeMounts:
        - mountPath: /opt/cerebro/conf
          name: cerebro-conf
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 9000
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 12
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 9000
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 50m
            memory: 512Mi
      volumes:
      - name: cerebro-conf
        configMap:
          name: cerebro
          items:
            - key: application.conf
              path: application.conf
