apiVersion: v1
kind: Secret
metadata:
  name: couchdb-cluster-admin
  labels:
    app: couchdb
    component: couchdb
    role: member
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: database       # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
type: Opaque
data:
  # echo -n 'admin' | base64
  #     YWRtaW4=
  username: YWRtaW4=
  # echo -n 'secret' | base64
  #     c2VjcmV0
  password: c2VjcmV0
