apiVersion: v1
kind: Secret
metadata:
  name: couchdb-cluster-admin
  namespace: default
type: Opaque
data:
  # echo -n 'admin' | base64
  #     YWRtaW4=
  username: YWRtaW4=
  # echo -n 'secret' | base64
  #     c2VjcmV0
  password: c2VjcmV0
