apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: ci
  labels:
    app: jenkins
    component: jenkins
    role: master
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: ci             # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
type: Opaque
data:
  # echo -n '--argumentsRealm.passwd.jenkins=jenkins --argumentsRealm.roles.jenkins=admin' | base64
  #    LS1hcmd1bWVudHNSZWFsbS5wYXNzd2QuamVua2lucz1qZW5raW5zIC0tYXJndW1lbnRzUmVhbG0ucm9sZXMuamVua2lucz1hZG1pbg==
  arguments: LS1hcmd1bWVudHNSZWFsbS5wYXNzd2QuamVua2lucz1qZW5raW5zIC0tYXJndW1lbnRzUmVhbG0ucm9sZXMuamVua2lucz1hZG1pbg==
