apiVersion: v1
kind: Secret
metadata:
  name: kibana
  namespace: kube-system
  labels:
    app: elk
    component: kibana
    role: ui
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: frontend       # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
type: Opaque
data:
  # htpasswd -c kibana.htpasswd kibana
  #    passwd:  kibana
  # cat kibana.htpasswd
  #    kibana:$apr1$sL9PyLyM$SgA1.leGIYk9bQ44aKErr1
  # echo -n 'kibana:$apr1$sL9PyLyM$SgA1.leGIYk9bQ44aKErr1' | base64
  #    a2liYW5hOiRhcHIxJHNMOVB5THlNJFNnQTEubGVHSVlrOWJRNDRhS0VycjE=
  htpasswd: a2liYW5hOiRhcHIxJHNMOVB5THlNJFNnQTEubGVHSVlrOWJRNDRhS0VycjE=
