apiVersion: v1
kind: Secret
metadata:
  name: kibana-oauth-google
  labels:
    app: elk
    component: kibana
    role: ui
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: frontend       # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
type: Opaque
data:
  # htpasswd -cs kibana.htpasswd kibana
  #    passwd:  kibana
  # cat kibana.htpasswd
  #    kibana:{SHA}gNQBXx9xGYyyhaidr5eW694LXCk=
  # echo -n 'kibana:{SHA}gNQBXx9xGYyyhaidr5eW694LXCk=' | base64
  # a2liYW5hOntTSEF9Z05RQlh4OXhHWXl5aGFpZHI1ZVc2OTRMWENrPQ==
  htpasswd: a2liYW5hOntTSEF9Z05RQlh4OXhHWXl5aGFpZHI1ZVc2OTRMWENrPQ==

  cookie-secret: WFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFg=
  client-id: WFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFg=
  client-secret: WFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFg=
