apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    component: rabbitmq
    role: message-bus
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: message-bus    # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
type: Opaque
data:
  # echo -n 'rabbitmq' | base64
  #     cmFiYml0bXE=
  username: cmFiYml0bXE=
  password: cmFiYml0bXE=

  #  echo -n 'monster' | base64
  #     bW9uc3Rlcg==
  cookie: bW9uc3Rlcg==
