---

- name: helm cli package status
  package:
    name: kubernetes-helm

- name: Create helm service account
  kubernetes:
    state:     present
    name:      tiller
    resource:  sa
    namespace: kube-system

- name: Create helm service account binding
  kubernetes:
    state:     present
    name:      "{{ rbac_namespace }}:tiller"
    resource:  clusterrolebinding
    options: >
      --clusterrole cluster-admin \
      --serviceaccount=kube-system:tiller

- name: tiler deployment status
  kubernetes:
    state:     status
    name:      tiller-deploy
    resource:  deployment
    namespace: kube-system
  register: tiler_status

- debug: var=tiler_status

- name: Initialize helm
  shell: >
    helm init --service-account tiller
  when: tiler_status.present == false