apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-public-lb-config
data:
  default.conf: |-
    upstream proxy-service {
      server couchdb:5984;
      keepalive 128;
    }

    geo $block_unknown_cidr {
        proxy  10.0.0.0/8;
        default              1;   # Block all by default
      # W.X.Y.Z/32           0;   # Allow this ip address
    }

    server {
      listen       80;

      location /index.html { alias /var/www/index.html; }

      location /_utils {
        if ($block_unknown_cidr) {
          return 444;
        }
        proxy_pass  http://proxy-service;
        proxy_redirect off;
        # proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Start $msec;
      }

      location ~ ^/$ { return 444; }
      location ~ ^/_ { return 444; }

      location / {
        proxy_pass  http://proxy-service;
        proxy_redirect off;
        # proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Start $msec;
      }

      location ~ ^/(.*)/_changes {
        proxy_pass  http://proxy-service;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Start $msec;
      }

    }

  index.html: |-
    <html>
      <head>
        <script type="text/javascript" src="//cdn.jsdelivr.net/pouchdb/6.1.2/pouchdb.min.js"></script>
        <script defer type="text/javascript">
          var localDB = new PouchDB('mylocaldb')
          var remoteDB = new PouchDB('http://192.168.99.100:5984/test-01')
          var opts = {live: true, retry: true};
          var syncHandle = localDB.sync(remoteDB, opts);

          function ok(evt) {
            var value = document.getElementById("text").value;
            var doc = {
                _id: new Date().toISOString(),
                text: value
              };
            localDB.put(doc, function callback(err, result) {
              if (err) return console.log('err:', err);
              console.log('Successfully posted a todo!');
            });            
          }
          function cancel() {
            syncHandle.cancel();
          }
        </script>
      </head>
      <body>
        <h1> PouchDB <==> CouchdB </h1>
        <label> Value
          <input id="text" type="field" value=""/>
        </label>
        <input type="button" value="OK" onclick="ok()"/>
        <input type="button" value="Cancel" onclick="cancel()"/>
      </body>
    </html>
s