---

- name: set namespace to {{ item }}
  set_fact:
    namespace: "{{ item }}"

- name: delete developer role for namespace {{namespace}}
  kubernetes:
    state:     absent
    name:      "{{ rbac_namespace }}:developer"
    resource:  role
    namespace: "{{ namespace }}"

- name: delete admin role for namespace {{namespace}}
  kubernetes:
    state:     absent
    name:      "{{ rbac_namespace }}:admin"
    resource:  role
    namespace: "{{ namespace }}"


- name: delete dockerhub credentials for namespace {{ namespace }}
  kubernetes:
    state:     absent
    name:      docker-hub-private-registry
    resource:  secret
    namespace: "{{ namespace }}"

- name: delete namespace {{namespace}}
  kubernetes:
    state:     absent
    name:      "{{ namespace }}"
    resource:  namespace
