apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cerebro
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: elk
        component: cerebro
        role: management
        release: stable      # stable, canary, alpha, beta, experimental, latest, debug
        environment: dev     # dev, staging, qa, production
        partition: all       # customer_1, customer_2, developer_1, beta_release
    spec:
      containers:
      - name: cerebro
        imagePullPolicy: Always # IfNotPresent, Always, Never
        image: yannart/cerebro:0.6.1
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 200Mi
        ports:
          - name: http
            containerPort: 9000
        volumeMounts:
        - mountPath: /opt/cerebro/conf
          name: cerebro-conf
      volumes:
      - name: cerebro-conf
        configMap:
          name: cerebro
          items:
            - key: application.conf
              path: application.conf
