kind: ConfigMap
apiVersion: v1
metadata:
  name: cerebro
  labels:
    app: elk
    component: cerebro
    role: ui-management
    release: stable      # stable, canary, alpha, beta, experimental, latest, debug
    environment: dev     # dev, staging, qa, production
    partition: all       # customer_1, customer_2, developer_1, beta_release
data:
  application.conf: |
    # This is the main configuration file for the application.
    # ~~~~~

    # Secret key
    # ~~~~~
    # The secret key is used to secure cryptographics functions.
    # If you deploy your application to several instances be sure to use the same key!
    play.crypto.secret="ki:s:[[@=Ag?QI`W2jMwkY:eqvrJ]JqoJyi2axj3ZvOv^/KavOT4ViJSv?6YY4[N"

    # The application languages
    # ~~~~~
    play.i18n.langs=["en"]

    play.modules.enabled += "controllers.auth.Module"
    play.modules.enabled += "elastic.ElasticModule"

    hosts = [
      #{
      #  host = "http://some-authenticated-host:9200"
      #  name = "Secured Cluster"
      #  auth = {
      #    username = "username"
      #    password = "secret-password"
      #  }
      #},
      #{
      #  host = "http://localhost:9200"
      #  name = "Some Cluster"
      #}
      {
       host = "http://elasticsearch:9200"
       name = "ELK - system diagnostic"
      }
    ]

    auth {
    #   type: ldap
    #     settings: {
    #       url = "ldap://host:port"
    #       base-dn = "ou=active,ou=Employee"
    #       method  = "simple"
    #       user-domain = "domain.com"
    #     }
    #   type: basic
    #   settings: {
    #     username = "admin"
    #     password = "1234"
    #   }
    }

    rest.history.size: 50 // defaults to 50 if not specified
    data.path: "./cerebro.db"

    slick.dbs.default.driver="slick.driver.SQLiteDriver$"
    slick.dbs.default.db.driver=org.sqlite.JDBC
    slick.dbs.default.db.url="jdbc:sqlite:"${data.path}
    play.evolutions.db.default.autoApply = true
