---

- name: mkdir {{ kubernetes.root.path }}/{{ namespace }}
  file:
    path: "{{ kubernetes.root.path }}/{{ namespace }}/"
    state: directory

- name: copy {{ resource }} templates for {{ namespace }}
  copy: 
    src: "files/"
    dest: "{{ kubernetes.root.path }}/{{ namespace }}/"

- name: render rabbitmq {{ ressouce }} templates for {{ namespace }}
  template:
    src: "rabbitmq-{{ ressouce }}.yaml.j2"
    dest: "{{ kubernetes.root.path }}/{{ namespace }}/rabbitmq-{{ ressouce }}.yaml"
  with_items:
    - ingress
  loop_control:
    loop_var: ressouce

- name: rabbitmq secret configuration
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      rabbitmq
    resource:  secret
    namespace: "{{ namespace }}"
    manifest:  "gs://{{ vault.root.path }}/{{ namespace }}/rabbitmq/rabbitmq-secret.yaml"

- name: deploy rabbitmq {{ resource }} in {{ namespace }}
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      "rabbitmq-{{ resource }}"
    resource:  "{{ resource }}"
    namespace: "{{ namespace }}"
    manifest:  "{{ kubernetes.root.path }}/{{ namespace }}/rabbitmq-{{ resource }}.yaml"
  with_items:
    - statefulset
    - service
  loop_control:
    loop_var: resource

- name: deploy rabbitmq discovery {{ resource }} in {{ namespace }}
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      "rabbitmq-discovery-{{ resource }}"
    resource:  "{{ resource }}"
    namespace: "{{ namespace }}"
    manifest:  "{{ kubernetes.root.path }}/{{ namespace }}/rabbitmq-discovery-{{ resource }}.yaml"
  with_items:
    - service
  loop_control:
    loop_var: resource
