apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: message-bus
        component: rabbitmq
        role: master
        release: stable      # stable, canary, alpha, beta, experimental, latest, debug
        environment: dev     # dev, staging, qa, production
        partition: all       # customer_1, customer_2, developer_1, beta_release
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: rabbitmq
        image: hbouvier/rabbitmq-kubernetes:3.6.6-management
        imagePullPolicy: Always
        # command: ["docker-entrypoint.sh"]
        # args: ["rabbitmq-server"]
        env:
        # - name: RABBITMQ_USE_LONGNAME
        #   value: "true"
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: cookie
        ports:
        - containerPort: 5672
          name: data
        - containerPort: 4369
          name: epmd
        - containerPort: 15672
          name: http
        - containerPort: 25672
          name: discovery
        readinessProbe:
          failureThreshold: 30
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 1
            memory: 512Mi
  #       volumeMounts:
  #       - mountPath: /var/lib/rabbitmq
  #         name: data
  #     volumes:
  #     - name: data
  #       persistentVolumeClaim:
  #         claimName: data

  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #     annotations:
  #       volume.beta.kubernetes.io/storage-class: aws-ebs-encrypted-ssd
  #       # volume.alpha.kubernetes.io/storage-class: ebs-ssd-encrypted
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 16Gi
