apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ci
  labels:
    component: jenkins
    role: master
  annotations:
    # AWS Managed cert ARN
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:000000000000:certificate/00000000-0000-0000-0000-000000000000"
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: ci
    component: jenkins
    role: master
  ports:
  - port: 80          # use   443     if you use an SSL Cert managed by AWS
    name: web-ui
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  namespace: ci
  labels:
    component: jenkins
    role: master
spec:
  selector:
    app: ci
    component: jenkins
  ports:
  - port: 50000
    name: slaves
    protocol: TCP
    targetPort: 50000
