apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: elk
    component: elasticsearch-interal-lb
    role: load-balancer
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: lb             # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
    name: http
  - port: 9300
    protocol: TCP
    targetPort: 9300
    name: transport
  selector:
    app: elk
    component: elasticsearch
