---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-container
  namespace: kube-system
  labels:
    app: elk
    component: filebeat-container
    role: collect-container-log
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: daemon         # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
data:
  filebeat.yml: |-
    filebeat:  
      prospectors:
        -
          paths:
            - "/var/log/containers/*.log"
          input_type: log
          document_type: kube_logs
    output:  
      logstash:
        hosts: ["logstash.kube-system.svc.cluster.local:5044"]
