apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-conf
  namespace: kube-system
  labels:
    app: elk
    component: nginx
    role: proxy
    release: stable      # canary
    environment: staging # dev, qa, production
    tier: daemon         # frontend, backend, cache
    partition: all       # customer_1, customer_2, developer_1, beta_release
data:
  default.conf: |-
    upstream proxy-service {
      server kibana-internal-lb.kube-system.svc.cluster.local:5601;
      keepalive 128;
    }

    server {
      listen       80;
      location / {
        auth_basic "Restricted";                               #For Basic Auth
        auth_basic_user_file /etc/nginx/htpasswd.d/.htpasswd;  #For Basic Auth
        proxy_pass  http://proxy-service;
        proxy_http_version 1.1;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection upgrade;
        proxy_set_header Connection "";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Start $msec;
      }
    }