kind: ConfigMap
apiVersion: v1
metadata:
  name: kibana
  labels:
    app: elk
    component: kibana
    role: dashboard
    release: stable      # stable, canary, alpha, beta, experimental, latest, debug
    environment: dev     # dev, staging, qa, production
    partition: all       # customer_1, customer_2, developer_1, beta_release
data:
  oauth2_proxy.cfg: |
    ## OAuth2 Proxy Config File

    cookie_name = "_oauth2_proxy"
    cookie_domain = "kibana.cluster.local"
    cookie_expire = "1h"
    cookie_refresh = "15m"
    cookie_httponly = true

    # cookie_secure = true
    cookie_secure = false # REMOVE ME FOR HTTPs

    # email_domains = [
    #   "localhost"
    # ]

    ## the OAuth Redirect URL.
    # defaults to the "https://" + requested host header + "/oauth2/callback"
    # redirect_url = "https://internalapp.yourcompany.com/oauth2/callback"

    ## Authenticated Email Addresses File (one email per line)
    # authenticated_emails_file = ""

    ## Htpasswd File (optional)
    ## Additionally authenticate against a htpasswd file. Entries must be created with "htpasswd -s" for SHA encryption
    ## enabling exposes a username/login signin form
    htpasswd_file = "/etc/oauth2_proxy/passwords/.htpasswd"

