apiVersion: v1
kind: ConfigMap
metadata:
  name: es-nginx-template
  annotations:
    konfd.io/kind: configmap
    konfd.io/name: es-nginx
    konfd.io/key:  default.conf
  labels:
    konfd.io/template: "true"
    app: elk
    component: elasticsearch
    role: client
data:
  template: |-
    upstream elasticsarch {
      server 127.0.0.1:9200;
      keepalive 15;
    }

    server {
      listen       80;

      location / {
        {{- $keys := secrets "es-users" -}}
        {{- if $keys.auth_basic }}
        auth_basic "Restricted Elasticsearch";
        auth_basic_user_file /etc/nginx/passwords/.htpasswd;
        {{ end -}}

        proxy_pass  http://elasticsarch;
        proxy_http_version 1.1;
        proxy_set_header Connection "Keep-Alive";
        proxy_set_header Proxy-Connection "Keep-Alive";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Start $msec;
      }
    }
