---
- name: Verify Google Cloud CLI tools installation
  shell: which gcloud
  ignore_errors: true
  register: gcloud_installation

- name: Install Google Cloud CLI tools
  shell: |
    which wget || brew install wget
    export GSDK_VERSION=158.0.0
    wget "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GSDK_VERSION}-darwin-x86_64.tar.gz" -P ~/Downloads/
    cd ${HOME}/Applications/
    tar xzf "${HOME}/Downloads/google-cloud-sdk-${GSDK_VERSION}-darwin-x86_64.tar.gz" && rm "${HOME}/Downloads/google-cloud-sdk-${GSDK_VERSION}-darwin-x86_64.tar.gz"
    cd google-cloud-sdk
    ./install.sh --disable-prompts
    cd
    gcloud init
    yes | gcloud components install alpha
  register: gcloud_install
  when: gcloud_installation.rc != 0

- debug: var=gcloud_install.stdout_lines
  when: '"gcloud not found" in gcloud_installation.stdout'

- name: Install kubectl CLI
  shell: >
    which kubectl || gcloud components install kubectl

- name: Verify kubectx CLI installation
  shell: which kubectx
  ignore_errors: true
  register: kubectx_installation

- name: Install kubectx CLI
  shell: |
    brew tap ahmetb/kubectx https://github.com/ahmetb/kubectx.git
    brew install kubectx
    which kubectx
  register: kubectx_install
  when: kubectx_installation.rc != 0

