apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: elk
    component: kibana
    role: dashboard
spec:
  selector:
    app: elk
    component: kibana
    role: dashboard
  ports:
  - port: 5601
    name: http
    protocol: TCP
