---

- name: mkdir {{ kubernetes.root.path }}/{{ namespace }}
  file:
    path: "{{ kubernetes.root.path }}/{{ namespace }}/"
    state: directory

- name: copy {{ resource }} templates for {{ namespace }}
  copy: 
    src: "files/"
    dest: "{{ kubernetes.root.path }}/{{ namespace }}/"

- name: deploy logstash {{ resource }} in {{ namespace }}
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      "logstash-{{ resource }}"
    resource:  "{{ resource }}"
    namespace: "{{ namespace }}"
    manifest:  "{{ kubernetes.root.path }}/{{ namespace }}/logstash-{{ resource }}.yaml"
  with_items:
    - configmap
    - deployment
    - service
  loop_control:
    loop_var: resource

- name: deploy filebeat log {{ resource }} in {{ namespace }}
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      "filebeat-log-{{ resource }}"
    resource:  "{{ resource }}"
    namespace: "{{ namespace }}"
    manifest:  "{{ kubernetes.root.path }}/{{ namespace }}/filebeat-log-{{ resource }}.yaml"
  with_items:
    - configmap
    - daemonset
  loop_control:
    loop_var: resource

- name: deploy filebeat container {{ resource }} in {{ namespace }}
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      "filebeat-container-{{ resource }}"
    resource:  "{{ resource }}"
    namespace: "{{ namespace }}"
    manifest:  "{{ kubernetes.root.path }}/{{ namespace }}/filebeat-container-{{ resource }}.yaml"
  with_items:
    - configmap
    - daemonset
  loop_control:
    loop_var: resource

- name: deploy journald {{ resource }} in {{ namespace }}
  kubernetes:
    state:     "{{ deploy_state }}"
    name:      "journald-{{ resource }}"
    resource:  "{{ resource }}"
    namespace: "{{ namespace }}"
    manifest:  "{{ kubernetes.root.path }}/{{ namespace }}/journald-{{ resource }}.yaml"
  with_items:
    - daemonset
  loop_control:
    loop_var: resource
