apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-container
spec:
  template:
    metadata:
      name: filebeat-container-logs
      labels:
        app: elk
        component: filebeat
        role: collect-container-logs
    spec:
      containers:
      - name: filebeat-container
        imagePullPolicy: Always
        image: hbouvier/filebeat-kubernetes:1.2.3
        volumeMounts:
        - name: filebeat-config-dir
          mountPath: /etc/filebeat/
        - name: varlog
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers/
          readOnly: true
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 12
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 50m
            memory: 512Mi
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-config-dir
        configMap:
          name: filebeat-container-logs
          items:
          - key: filebeat.yml
            path: filebeat.yml
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers/
