apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-log
spec:
  template:
    metadata:
      name: filebeat-system-logs
      labels:
        app: elk
        component: logstash
        role: collect-system-logs
    spec:
      containers:
      - name: filebeat
        imagePullPolicy: Always
        image: hbouvier/filebeat-kubernetes:1.2.3
        volumeMounts:
        - name: filebeat-config-dir
          mountPath: /etc/filebeat/
        - name: varlog
          mountPath: /var/log
        - name: root
          mountPath: /filebeat-logs/root
          readOnly: true
        - name: home
          mountPath: /filebeat-logs/home
          readOnly: true
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 12
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 50m
            memory: 512Mi
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-config-dir
        configMap:
          name: filebeat-system-logs
          items:
          - key: filebeat.yml
            path: filebeat.yml
      - name: varlog
        hostPath:
          path: /var/log
      - name: root
        hostPath:
          path: /root
      - name: home
        hostPath:
          path: /home
