apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: message-bus
    component: rabbitmq
    role: broker
spec:
  ports:
  - port: 5672
    name: data
  - port: 15672
    name: http
  selector:
    app: message-bus
    component: rabbitmq
    role: broker
